[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gasp-pip-tutorial"
version = "0.1"
readme = "README.md"
dependencies = [
    "numpy~=1.26.4"
]

[tool.setuptools.packages.find]
where = ["src"]
